# Generated by Django 3.1.3 on 2020-11-18 18:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpost_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ghost',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
