# Generated by Django 3.1.3 on 2020-11-18 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpost_app', '0002_ghost_created_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ghost',
            new_name='GhostPost',
        ),
    ]
