# Generated by Django 3.1.3 on 2020-11-18 19:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpost_app', '0005_ghostpost_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ghostpost',
            name='created_at',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
