# Generated by Django 3.1.3 on 2020-11-18 19:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpost_app', '0006_auto_20201118_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ghostpost',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
