# Generated by Django 3.1.3 on 2020-11-18 19:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpost_app', '0007_auto_20201118_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ghostpost',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
