# Generated by Django 3.1.3 on 2020-11-18 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpost_app', '0009_auto_20201118_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ghostpost',
            name='ghostpost',
        ),
    ]
