# Generated by Django 3.1.3 on 2020-11-18 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpost_app', '0010_remove_ghostpost_ghostpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='ghostpost',
            name='ghostpost',
            field=models.BooleanField(default=False),
        ),
    ]
