# Generated by Django 3.1.3 on 2020-11-19 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpost_app', '0011_ghostpost_ghostpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ghostpost',
            name='text',
            field=models.CharField(max_length=100),
        ),
    ]
