# Generated by Django 3.1.3 on 2020-11-19 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpost_app', '0014_ghostpost_ghostpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ghostpost',
            name='ghostpost',
            field=models.BooleanField(default=True),
        ),
    ]
